### PR TITLE
Some typos in Custom Regions

### PR DESCRIPTION
**Pull request by chkworks**

### CODE REVIEW

**Comment by chkworks** [comment]
Also under "Stateful - delegate-based" the following is written:

_Often enough those regions only manage one instance of the users' patch, but in theory such a region can also manage the whole lifetime of many instances those patches._

Seems something is missing in the second half of the sentence?

**Comment by chkworks** [comment]
Hey, have you seen my latest comment also?

**Comment by gregsn** [comment]
Ah yes. Thanks

**Comment by gregsn** [comment]
continued: https://github.com/vvvv/The-Gray-Book/pull/51

**Pull request merged**
